# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='sensorendpoint',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.Credential'),
        ),
        migrations.AddField(
            model_name='generated',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intake.SensorEndpoint'),
        ),
    ]
