# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorendpoint',
            name='name',
            field=models.CharField(default='Name!', max_length=50),
            preserve_default=False,
        ),
    ]
