# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20170611_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='sensorendpoint',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='intake.SensorSite'),
            preserve_default=False,
        ),
    ]
