# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_sensorendpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorendpoint',
            name='last_retrieved',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
