# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:20
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_sensorendpoint_last_retrieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorendpoint',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='US/Mountain'),
        ),
    ]
