# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_sensorendpoint_timezone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='generated',
            unique_together=set([('timestamp', 'sensor')]),
        ),
    ]
